### ISSUE TITLE
Create a release document for RBM V2.2

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/RBM#15]
See: https://github.com/UW-Hydro/VIC/issues/589 as an example

**Comment by YifanCheng** [comment]
1) a Water_Balance subroutine is added to handle VIC baseflow/runoff that is not accounted for by tributary inflow.
2) update Systmm.f90 energy budget computation to account for the additional inflow
3) set up RBM documentation website 
4) set up automatic code testing (Travis CI)

**Comment by YifanCheng** [comment]
Have updated in the milestone (2.2.0) description. 

Fixed it!
